services:
  - type: web
    name: coffee-order-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://coffee-app-backend-rg3h.onrender.com/api

